### ISSUE TITLE
how to get "cifar10_parameters_nb.zip" from my own training parameters?

### ISSUE THREAD

**Issue by manymuch** [cornell-zhang/bnn-fpga#12]
The ParamsIO.cpp and ZipIO.cpp load *.zip file as parameters. If I want to use my own training parameters, for example, generated by numpy.savez(_compressed) as *.npz,
how do I get *.zip  from *.npz?

**Comment by rzhao01** [comment]
There is a script in https://github.com/cornell-zhang/bnn-fpga/tree/master/python which converts .npz to .zip
