### ISSUE TITLE
Timing constraints are not met

### ISSUE THREAD

**Issue by hex0102** [cornell-zhang/bnn-fpga#13]
Hi all, after I build the FPGA bitstream with the default project, I always got Timing constraints are not met. Is there any possible solution to this issue?

**Comment by rzhao01** [comment]
The design does not meet timing for us either, however it still works on the board.

**Comment by hex0102** [comment]
@rzhao01 any clues to this issue? And what's the working frequency of the accelerator?

**Comment by rzhao01** [comment]
We used a clock period of 7ns, which allows the accelerator to work on the Zedboard.

**Comment by hex0102** [comment]
@rzhao01 Thanks, I can also deploy the accelerator to ZC702 board now.  I'm still curious why the sdsoc reports "timing not met".

**Comment by rzhao01** [comment]
SDSoC and other HLS tools use a timing model which is pessimistic. Failing timing in the tool does not necessarily mean failing on an actual board (it may fail on some boards and work on others). If timing is met in the HLS tool then the design is guaranteed to work on the board.

Of course we prefer to pass timing in the HLS tool but in this case we could not get that to happen.
