### ISSUE TITLE
make: sds++: Command not found

### ISSUE THREAD

**Issue by eelgin** [cornell-zhang/bnn-fpga#17]
When I run `make -j4` on the fpga bitstream I keep getting this build error. Anyone ever run into this?
![sds](https://user-images.githubusercontent.com/11166304/37868398-07638746-2f7c-11e8-8050-a770cc926a83.png)
My setup follows the recommendation with Ubuntu 16.04 and SDSoC 2016.4

**Comment by rzhao01** [comment]
You don't have SDSoC installed or your environment is not properly set up for SDSoC. There should be a settings.sh file (or something similar) in the SDSoC install directory to set up the environment.
