### ISSUE TITLE
details about bin_dense()

### ISSUE THREAD

**Issue by manymuch** [cornell-zhang/bnn-fpga#21]
I couldn't understand these codes, [Accel.cpp#L624](https://github.com/cornell-zhang/bnn-fpga/blob/master/cpp/accel/Accel.cpp#L624). And h01 [Accel.cpp#L10](https://github.com/cornell-zhang/bnn-fpga/blob/master/cpp/accel/Accel.cpp#L10) seems not being used. Could you please give a hint? Thanks so much!

**Comment by rzhao01** [comment]
It's an implementation of bitcount which doesn't use loops. Here are some references: [1](http://aggregate.ee.engr.uky.edu/MAGIC/#Population%20Count%20(Ones%20Count)) [2](http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetNaive)

**Comment by manymuch** [comment]
I see. Thanks!
