### ISSUE TITLE
max_align_t problem

### ISSUE THREAD

**Issue by qingzengsong** [cornell-zhang/bnn-fpga#5]
when mak in cpp，I have a problem ‘’max_align_t‘’.
In file included from /opt/Xilinx/SDx/2016.4/Vivado_HLS/include/gmp.h:53:0,
                 from /opt/Xilinx/SDx/2016.4/Vivado_HLS/include/floating_point_v7_0_bitacc_cmodel.h:143,
                 from /opt/Xilinx/SDx/2016.4/Vivado_HLS/include/hls_half.h:40,
                 from /opt/Xilinx/SDx/2016.4/Vivado_HLS/include/ap_int.h:28,
                 from ../utils/Typedefs.h:4,
                 from AccelTest.h:4,
                 from AccelTest.cpp:1:
/usr/include/c++/5/cstddef:51:11: error: ‘::max_align_t’ has not been declared
   using ::max_align_t;
           ^

I add #include <cstddef> to 
ParamIO.cpp
Common.cpp
DataIO.cpp
AccelTest.cpp
  can solve this problem.

But, this wether lead other problem, since 
'ParamIO.cpp
Common.cpp
DataIO.cpp
AccelTest.cpp'
will be build by Vivado_HLS?

**Comment by MinLiAmoy** [comment]
I met the same problem. I added #include <cstddef> and the problem was solved. There's no problem with the SDSoC.

**Comment by qingzengsong** [comment]
But I have the problem since #include with the sdsoc.
There is error，

发自我的 iPhone

**Comment by qingzengsong** [comment]
Pragma processor failed: In file included from /home/songqingzeng/bnn-fpga-master/cpp/accel/Accel.cpp:1:
the Accel.cpp :1
is "#include "


发自我的 iPhone

**Comment by yunchenlo** [comment]
@qingzengsong  @MinLiAmoy 
May I know what specifically should I change to solve this problem, thanks!
Jason Lo

**Comment by rzhao01** [comment]
Looking online, the solution is to do
`#include<cstddef>`
before any other headers.

**Comment by hex0102** [comment]
I added #include \<cstddef\> in every .cpp file in both **utils** and **accel**. It seems work.
