### ISSUE TITLE
run make -j4 for sdsoc_build makefile, xdlmcheck is not found

### ISSUE THREAD

**Issue by liyoungforever** [cornell-zhang/bnn-fpga#7]
Hi！ When I run make -j4 command for the sdsoc_build makefile,  I have a issue.  I used Ubuntu 16.04 OS, 2017.1 SDSoc software. 

![screenshot from 2017-10-05 15-45-44](https://user-images.githubusercontent.com/32550259/31250538-0ab24d1a-a9e9-11e7-8343-a8cf8d6bea08.png)

when I run xdlmcheck ap_sdsoc command, it shows the same problem with my SDSOC
![screenshot from 2017-10-05 15-58-17](https://user-images.githubusercontent.com/32550259/31250590-3eaa130a-a9e9-11e7-8186-d7705d9caad9.png)

Thank you!

**Comment by rzhao01** [comment]
I don't think I've ever encountered this issue, but it looks like an issue with the SDSoC installation to me. It looks like the SDSoC tool is looking for a program and was not able to find it. Did you make sure to set up the environment for SDSoC?

**Comment by LiYang66** [comment]
Thank you! My issue has been solved! Appreciated!

**Comment by liyoungforever** [comment]
Thank you! My issue has been solved!
